### ISSUE TITLE
CI test in Different Linux Distros

### ISSUE THREAD

**Issue by xuhang57** [cyverse/clank#244]
Someone has suggested me with using: https://molecule.readthedocs.io/en/latest/

A benefit is "You can specify the Docker images for both inside the molecule/scenario/tests/molecule.yml, install molecule within Travis CI in install:, and then just molecule test in your script: to do the heavy lifting for you."

I will later spend some time testing this. And hope this can solve the CI test for CentOS issue related to this PR:https://github.com/cyverse/clank/pull/206

Any opinion is more than welcome :)

**Comment by xuhang57** [comment]
https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis 

A Travis blog and it talks about how to use Docker containers (both ubuntu and centos) to test ansible roles.

**Comment by c-mart** [comment]
@xuhang57, I've been doing multi-distro testing of new Ansible roles that way (using Docker on Travis CI) for the past year or so. Jeff Geerling wrote about the technique [here](https://www.jeffgeerling.com/blog/2016/how-i-test-ansible-configuration-on-7-different-oses-docker) (describes essentially the same thing as your link). From that I made an [Ansible role template](https://github.com/cyverse-ansible/ansible-role-template) with boilerplate that makes it much faster to set up, and gives you some basic tests for free. I use this for every new Galaxy role that I create (though sometimes don't bother to write role-specific tests).

When it works, it works, *but* a lot of the Ansible roles that I deal with configure "systems-y" things which don't work on a stock Docker container. I found myself trying to install systemd and SSH server in the containers in order to make them behave more like a full system (so I can test roles which do things like install/restart services), and it's not a good time. At this point I'd rather be testing roles on full VMs than Docker containers, which rules out Travis CI if we want to test anything other than Ubuntu 14.04. I'm encouraged by Molecule's [multi-driver support](https://molecule.readthedocs.io/en/latest/configuration.html#driver), including OpenStack, which would take care of "where do I run the VMs for testing?" I just haven't made the time to dig into it.

**Comment by xuhang57** [comment]
Thanks for these great thoughts @c-mart !  So, it makes sense to me when you said "rather be testing roles on full VMs". I have the similar feeling. 

My goal is to let `clank` run on CentOS7 as well. Making the CI supports it is the next step (maybe fix the conflicts should be the next). Looks like the `Molecule` might be our solution here. We shall see. I will update the experience with using it later (same situation here; working on many other things at the same time is not really productive to me :( ). Thanks for your reply!
